# Generated by Django 3.2.5 on 2024-12-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(upload_to='blog_image/%Y/%m/%d/'),
        ),
    ]
